# Generated by Django 6.0.2 on 2026-02-15 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_comments_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='comments',
            constraint=models.UniqueConstraint(fields=('post', 'content'), name='unique_comment_text_per_post'),
        ),
    ]
